// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aNRXXTOvO2ZE4veV54iIBaxlFe3kDOU',
    appId: '1:1093981067133:web:1b8849034eaa7329291e14',
    messagingSenderId: '1093981067133',
    projectId: 'prueba-df7ab',
    authDomain: 'prueba-df7ab.firebaseapp.com',
    storageBucket: 'prueba-df7ab.appspot.com',
    measurementId: 'G-F054E2WJJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCedP0JJWb0w1C5EPsVD7xIVDM7-fXf6IE',
    appId: '1:1093981067133:android:f901af221c02ebfc291e14',
    messagingSenderId: '1093981067133',
    projectId: 'prueba-df7ab',
    storageBucket: 'prueba-df7ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEvh14xOckG5mwLAW3LLsQ-BdCR2E55eA',
    appId: '1:1093981067133:ios:df3ef602ee77d6a1291e14',
    messagingSenderId: '1093981067133',
    projectId: 'prueba-df7ab',
    storageBucket: 'prueba-df7ab.appspot.com',
    androidClientId: '1093981067133-oit6o7f4c75v9lg5h1ho51a7bvk6fsc6.apps.googleusercontent.com',
    iosClientId: '1093981067133-14hppf58bgbcsh38qrfcb0fftj69uqt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ijandula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEvh14xOckG5mwLAW3LLsQ-BdCR2E55eA',
    appId: '1:1093981067133:ios:f944171cb38ef533291e14',
    messagingSenderId: '1093981067133',
    projectId: 'prueba-df7ab',
    storageBucket: 'prueba-df7ab.appspot.com',
    androidClientId: '1093981067133-oit6o7f4c75v9lg5h1ho51a7bvk6fsc6.apps.googleusercontent.com',
    iosClientId: '1093981067133-lk4egjf9mqu946pibuar2qb416sq7m4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ijandula.RunnerTests',
  );
}
